# 这个 app 名称必须替换为你在 Fly.io 后台创建的名字
app = "thrumming-island-597"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"
  
[env]
  SCHEDULER_ENABLED = "true"
  SCHEDULER_TRIGGER = "Wednesday 19:00" # 这里可以设置你想要的正式匹配时间

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
